import random
import pygame, sys, os
from pygame.locals import *
import argparse
import math

BACKGROUND_COLOR = (95,158,160)
WIDTH = 1280
HEIGHT = 720
PLAYER_DIMENSIONS = (WIDTH // 10, HEIGHT // 4)
PLAYER_VELOCITY = 13
SHURIKEN_DIMENSIONS = (WIDTH // 30, HEIGHT // 10)
SHURIKEN_SPEED = 10
BALLOON_SPEED = 5
BALLOON_DIMENSIONS = (WIDTH // 20, HEIGHT // 7)
ARROW_INITIAL_SPEED = 10
ARROW_MAX_SPEED = 17
ARROW_DIMENSIONS = (WIDTH // 20, HEIGHT // 15)
CLOUD_SPEED = 8
CLOUD_DIMENSIONS = (WIDTH // 15, HEIGHT // 5)
SPEED_INCREASE = 0.2
SHURIKEN_POINTS = 30
CLOUD_POINTS = 15
BALLON_POINTS = 20
LIFE = 3
SCORE = 0
